#NumPy

##1. How to extract all odd numbers from arr?


In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4,5, 6, 7, 8, 9])
x=np.where(arr%2==1)
print(arr[x])

[1 3 5 7 9]


##2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##3.  Convert a 1D array to a 2D array with 2 rows



In [ ]:
import numpy as np
arr=np.arange(10).reshape(2,5)
print(arr)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##4. Stack arrays a and b vertically



In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
newarr=np.vstack((a,b))
print(newarr)


[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##5. Stack the arrays a and b horizontally.



In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
newarr=np.hstack((a,b))
print(newarr)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


##6.How to get the common items between two python numpy arrays?
Get the common items between a and b




In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items=np.intersect1d(a,b)
print(common_items)

[2 4]


##7.How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result=np.setdiff1d(a,b)
print(result)


[1 2 3 4]


##8. How to get the positions where elements of two arrays match?

Q. Get the positions where elements of a and b match



In [ ]:
import numpy as np

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

matching_positions = np.where(a == b)
print("Positions where elements of both arrays match:", matching_positions)


Positions where elements of both arrays match: (array([1, 3, 5, 7]),)


##9. How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a

In [ ]:
#using list comprehension method
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
newarr=np.array([x for x in a if 5 <= x <=10])

print(newarr)

[ 6  9 10]


In [ ]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
indices=np.where((a>=5) & (a<=10))
result=(a[indices],)
print(result)

#Desired Output:

#(array([6, 9, 10]),)

(array([ 6,  9, 10]),)


#Pandas

##Pandas Data Series

##1. Write a Pandas program to convert a dictionary to a Pandas series.

```
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64

```

In [ ]:
import pandas as pd
data_set={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
myvar=pd.Series(data_set)
print(myvar)

a    100
b    200
c    300
d    400
e    800
dtype: int64


##2. Write a Pandas program to convert a NumPy array to a Pandas series.
```
Sample Series:
  NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

```

In [ ]:
import pandas as pd
array=[10,20,30,40,50]
array_series=pd.Series(array)
print(array_series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


##3. Write a Pandas program to change the data type of given a column or a Series.

```
Sample Series:
    Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

```

In [ ]:
import pandas as pd

# Sample Series
data_series = pd.Series([100, 200, 'python', 300.12, 400])

# Change data type to numeric
converted_series = pd.to_numeric(data_series,errors='coerce')
#When errors='coerce' is set:If any value in the series cannot be converted to a numeric type, it will be replaced with NaN
print(converted_series)


0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


##4. Write a Pandas program to convert the first column of a DataFrame as a Series.

```
Sample Output:  
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>

```

In [ ]:
import pandas as pd
data_series={'col1':[1,2,3,4,7,11],
             'col2':[4,5,6,9,5,0],
             'col3':[7,5,8,12,1,11]
             }
df=pd.DataFrame(data_series)
print(df['col1'])


0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


##5. Write a Pandas program to convert a given Series to an array.

```
Sample Output:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']
<class 'numpy.ndarray'>

```

In [ ]:
import pandas as pd
data=pd.Series([100,200,'python',300.12,400])
array_data=data.values
print("Original Data Series:")
print(data)
print("\nSeries to an array\n",array_data)
print(type(array_data))

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array
 [100 200 'python' 300.12 400]
<class 'numpy.ndarray'>


##6 Write a Pandas program to convert Series of lists to one Series.
```
Sample Output:
Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object
One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

```

In [ ]:
import pandas as pd
data_list=(['Red','Green','White'],['Red','Black'],['Yellow'])
new_series=pd.Series(data_list)
#covert into one series
flattened_series=new_series.explode().reset_index(drop=True) #reset the index to a default integer index and dropping the old index.

print("Original Series of list")
print(new_series)
print("\nOne series")
print(flattened_series)

Original Series of list
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object


##7.Write a Pandas program to sort a given Series.
```
Sample Output:
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object
```

In [ ]:
import pandas as pd

# Create a sample Pandas Series
data = pd.Series([100, 200, 'python', 300.12, 400])

# Print the original Series
print("Original Data Series:")
print(data)

# Convert all elements to strings and then sort the Series
sorted_data = data.astype(str).sort_values()

# Print the sorted Series
print("\nSorted Data Series:")
print(sorted_data)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted Data Series:
0       100
1       200
3    300.12
4       400
2    python
dtype: object


##Pandas DataFrame

##1.Write a Pandas program to create a dataframe from a dictionary and display it.
```
Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
Expected Output:
    X   Y   Z                                                         
0  78  84  86                                                        
1  85  94  97                                                         
2  96  89  96                                                      
3  80  83  72                                                         
4  86  86  83

```


In [ ]:
import pandas as pd
data={'X':[78,85,96,80,86],
      'Y':[84,94,89,83,86],
      'z':[86,97,96,72,83]}
df=pd.DataFrame(data)
print("Dictionary:",data)
print("Data frame:\n",df)

Dictionary: {'X': [78, 85, 96, 80, 86], 'Y': [84, 94, 89, 83, 86], 'z': [86, 97, 96, 72, 83]}
Data frame:
     X   Y   z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


##2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
   attempts       name qualify  score                              
a         1  Anastasia     yes   12.5                                 
b         3       Dima      no    9.0                                 
....                              
i         2      Kevin      no    8.0                                
j         1      Jonas     yes   19.0

```

In [ ]:
import pandas as pd
import numpy as np
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
            'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
            'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
            'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
             }
df=pd.DataFrame(exam_data,index=labels)
print('Exam data:\n',df)

Exam data:
         name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


##3. Write a Pandas program to get the first 3 rows of a given DataFrame.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
First three rows of the data frame:                                   
   attempts       name qualify  score                              
a         1  Anastasia     yes   12.5                                 
b         3       Dima      no    9.0                                 
c         2  Katherine     yes   16.5

```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Reorder columns to match the expected output
df = df[['attempts','name', 'qualify','score']]

# Get the first three rows of the DataFrame
first_three_rows = df.head(3)

# Display the result
print("First three rows of the data frame:")
print(first_three_rows)



First three rows of the data frame:
   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5


##4.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Select specific columns:                                               
        name  score                                                  
a  Anastasia   12.5                                                   
b       Dima    9.0                                                
c  Katherine   16.5                                                    
...                                                  
h      Laura    NaN                                                   
i      Kevin    8.0                                                  
j      Jonas   19.0
```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)
print("select specific columns:\n")
print(df[['name','score']])

select specific columns:

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


##5.  Write a Pandas program to select the specified columns and rows from a given data frame.
```
Sample Python dictionary data and list labels:
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Select specific columns and rows:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes

```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

#select specific rows
rows=df.loc[['b','d','f','g']]

#select specific columns
print("Select specific rows and columns:")
print(rows[['score','qualify']])

Select specific rows and columns:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes


##6. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

print("Number of attempts in the examination is greater than 2:")
print(df[df['attempts']>2])

Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


##7. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Rows where score is missing:
   attempts   name qualify  score
d         3  James      no    NaN
h         1  Laura      no    NaN

```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Reorder columns to match the expected output
df = df[['attempts','name', 'qualify','score']]


print("Rows where score is missing:")
print(df[df['score'].isna()])

Rows where score is missing:
   attempts   name qualify  score
d         3  James      no    NaN
h         1  Laura      no    NaN


##8. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Rows where score between 15 and 20 (inclusive):                        
   attempts       name qualify  score                                  
c         2  Katherine     yes   16.5                                
f         3    Michael     yes   20.0                                 
j         1      Jonas     yes   19.0
```


In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Reorder columns to match the expected output
df = df[['attempts','name', 'qualify','score']]

print("Rows where score between 15 and 20 (inclusive): ")
print(df[(df['score']>=15) & (df['score']<=20)])

Rows where score between 15 and 20 (inclusive): 
   attempts       name qualify  score
c         2  Katherine     yes   16.5
f         3    Michael     yes   20.0
j         1      Jonas     yes   19.0


##9. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Number of attempts in the examination is less than 2 and score greater than 15 :
    name  score  attempts qualify
j  Jonas   19.0         1     yes

```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

print("Number of attempts in the examination is less than 2 and score greater than 15 : ")
print(df[(df['attempts'] <2 ) & (df['score'] >=15)])

Number of attempts in the examination is less than 2 and score greater than 15 : 
    name  score  attempts qualify
j  Jonas   19.0         1     yes


##10. Write a Pandas program to change the score in row 'd' to 11.5.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

```

```
Expected Output:
Change the score in row 'd' to 11.5:                                  
   attempts       name qualify  score                                
a         1  Anastasia     yes   12.5                               
b         3       Dima      no    9.0                                
c         2  Katherine     yes   16.5
...                                
i         2      Kevin      no    8.0                                 
j         1      Jonas     yes   19.0

```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Reorder columns to match the expected output
df = df[['attempts','name', 'qualify','score']]

#Change the score in row 'd' to 11.5
df.loc['d','score']=11.5
print(df)

   attempts       name qualify  score
a         1  Anastasia     yes   12.5
b         3       Dima      no    9.0
c         2  Katherine     yes   16.5
d         3      James      no   11.5
e         2      Emily      no    9.0
f         3    Michael     yes   20.0
g         1    Matthew     yes   14.5
h         1      Laura      no    NaN
i         2      Kevin      no    8.0
j         1      Jonas     yes   19.0


##11. Write a Pandas program to calculate the sum of the examination attempts by the students.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Sum of the examination attempts by the students:                     
19
```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)
result=df['attempts'].sum()
print("Sum of the examination attempts by the students:")
print(result)

Sum of the examination attempts by the students:
19


##12. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Mean score for each different student in data frame:                  
13.5625
```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)
result=df['score'].mean()
print("Mean score for each different student in data frame:")
print(result)

Mean score for each different student in data frame:
13.5625


##13. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

```
Expected Output:
Replace the 'qualify' column contains the values 'yes' and 'no'  with T
rue and  False:                                                      
   attempts       name  qualify  score                              
a         1  Anastasia     True   12.5                          
b         3       Dima    False    9.0                              
......                           
i         2      Kevin    False    8.0                                 
j         1      Jonas     True   19.0
```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Reorder columns to match the expected output
df = df[['attempts','name', 'qualify','score']]
print("Replace the 'qualify' column contains the values 'yes' and 'no'  with True and  False: \n ")
# Replace 'yes' and 'no' with True and False
df['qualify'] = df['qualify'].replace({'yes': True, 'no': False})
print(df)

Replace the 'qualify' column contains the values 'yes' and 'no'  with True and  False: 
 
   attempts       name  qualify  score
a         1  Anastasia     True   12.5
b         3       Dima    False    9.0
c         2  Katherine     True   16.5
d         3      James    False    NaN
e         2      Emily    False    9.0
f         3    Michael     True   20.0
g         1    Matthew     True   14.5
h         1      Laura    False    NaN
i         2      Kevin    False    8.0
j         1      Jonas     True   19.0


##14. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Change the name 'James' to \?Suresh\?:                                
   attempts       name qualify  score                                  
a         1  Anastasia     yes   12.5                                  
b         3       Dima      no    9.0                                  
.......                               
i         2      Kevin      no    8.0                                 
j         1      Jonas     yes   19.0
```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

# Reorder columns to match the expected output
df = df[['attempts','name', 'qualify','score']]

print("Change the name 'James' to 'Suresh':\n ")
df['name']=df['name'].replace({'James':'Suresh'})
print(df)

Change the name 'James' to 'Suresh':
 
   attempts       name  qualify  score
a         1  Anastasia     True   12.5
b         3       Dima    False    9.0
c         2  Katherine     True   16.5
d         3     Suresh    False    NaN
e         2      Emily    False    9.0
f         3    Michael     True   20.0
g         1    Matthew     True   14.5
h         1      Laura    False    NaN
i         2      Kevin    False    8.0
j         1      Jonas     True   19.0


##15. Write a Pandas program to delete the 'attempts' column from the DataFrame.
```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
Delete the 'attempts' column from the data frame:                    
        name qualify  score                                          
a  Anastasia     yes   12.5                                           
b       Dima      no    9.0                                          
.....                                       
i      Kevin      no    8.0                                          
j      Jonas     yes   19.0
```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)

p=df.drop('attempts',axis=1)
print("Delete the 'attempts' column from the data frame:\n",p)

Delete the 'attempts' column from the data frame:
         name  qualify  score
a  Anastasia     True   12.5
b       Dima    False    9.0
c  Katherine     True   16.5
d     Suresh    False    NaN
e      Emily    False    9.0
f    Michael     True   20.0
g    Matthew     True   14.5
h      Laura    False    NaN
i      Kevin    False    8.0
j      Jonas     True   19.0


##16.  Write a Pandas program to insert a new column in existing DataFrame.

```
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
```
Expected Output:
New DataFrame after inserting the 'color' column                       
   attempts       name qualify  score   color                       
a         1  Anastasia     yes   12.5     Red                         
b         3       Dima      no    9.0    Blue                        
.......                     
i         2      Kevin      no    8.0   Green                        
j         1      Jonas     yes   19.0     Red
```

In [ ]:
import pandas as pd
import numpy as np

# Sample dictionary data and list labels
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
             'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
             'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
             'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

# Create DataFrame
df = pd.DataFrame(exam_data, index=labels)
# Reorder columns to match the expected output
df = df[['attempts','name', 'qualify','score']]

df['color']=['red','blue','red','pink','green','grey','brown','red','black','pink']
print("New DataFrame after inserting the 'color' column : \n\n",df)

New DataFrame after inserting the 'color' column : 

    attempts       name qualify  score  color
a         1  Anastasia     yes   12.5    red
b         3       Dima      no    9.0   blue
c         2  Katherine     yes   16.5    red
d         3      James      no    NaN   pink
e         2      Emily      no    9.0  green
f         3    Michael     yes   20.0   grey
g         1    Matthew     yes   14.5  brown
h         1      Laura      no    NaN    red
i         2      Kevin      no    8.0  black
j         1      Jonas     yes   19.0   pink


##17.  Write a Pandas program to rename columns of a given DataFrame

```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
New DataFrame after renaming columns:
   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9
```

In [ ]:
import pandas as pd
data={
    'col1':[1,2,3],
    'col2':[4,5,6],
    'col3':[7,8,9]
}
df=pd.DataFrame(data)
print("Original DataFrame:\n",df)
df=df.rename(columns={'col1':'Column1','col2':'Column2','col3':'Column3'})
print("New DataFrame after renaming columns:")
print(df)

Original DataFrame:
    col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9
New DataFrame after renaming columns:
   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9


##18. Write a Pandas program to select rows from a given DataFrame based on values in some columns.
```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
Rows for colum1 value == 4
   col1  col2  col3
1     4     5     8
3     4     7     0
```

In [ ]:
import pandas as pd
data={
    'col1': [1, 4, 3, 4, 5],
    'col2': [4, 5, 6, 7, 8],
    'col3': [7, 8, 9, 0, 1]
}
df=pd.DataFrame(data)
print("Original Data:\n",df)

print("Rows for colum1 value == 4")
selected_rows=df[df['col1']==4]
print(selected_rows)

Original Data:
    col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
Rows for colum1 value == 4
   col1  col2  col3
1     4     5     8
3     4     7     0


##19. Write a Pandas program to add one row in an existing DataFrame.

```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
After add one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12
```

In [ ]:
import pandas as pd

# Sample data
data = {
    'col1': [1, 4, 3, 4, 5],
    'col2': [4, 5, 6, 7, 8],
    'col3': [7, 8, 9, 0, 1]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# New row to add
new_row = {'col1': 10, 'col2': 11, 'col3': 12}
df_new_row=pd.DataFrame([new_row])

df=pd.concat([df,df_new_row],ignore_index=True)

print("\nAfter adding one row:")
print(df)


Original DataFrame:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

After adding one row:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12


##20. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.

```
Sample data:
Original DataFrame

   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

```
```

New DataFrame replacing all NaN with 0:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
.....
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
```

In [ ]:
import pandas as pd
import numpy as np

# Sample data
data = {
    'attempts': [1, 3, 2, np.nan, 2, 3, np.nan, 1, 2, 1],
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'score': [12.5, 9.0, 16.5, np.nan, 9.0, 20.0, 14.5, np.nan, 8.0, 19.0]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace NaN values with zeros in the 'score' column
df['score']=df['score'].fillna(0)
print("\nNew DataFrame replacing all NaN with 0:")
print(df)


Original DataFrame:
   attempts       name qualify  score
0       1.0  Anastasia     yes   12.5
1       3.0       Dima      no    9.0
2       2.0  Katherine     yes   16.5
3       NaN      James      no    NaN
4       2.0      Emily      no    9.0
5       3.0    Michael     yes   20.0
6       NaN    Matthew     yes   14.5
7       1.0      Laura      no    NaN
8       2.0      Kevin      no    8.0
9       1.0      Jonas     yes   19.0

New DataFrame replacing all NaN with 0:
   attempts       name qualify  score
0       1.0  Anastasia     yes   12.5
1       3.0       Dima      no    9.0
2       2.0  Katherine     yes   16.5
3       NaN      James      no    0.0
4       2.0      Emily      no    9.0
5       3.0    Michael     yes   20.0
6       NaN    Matthew     yes   14.5
7       1.0      Laura      no    0.0
8       2.0      Kevin      no    8.0
9       1.0      Jonas     yes   19.0


##21. Write a Pandas program to count the NaN values in one or more columns in DataFrame.
```
Sample data:
Original DataFrame
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Number of NaN values in one or more columns:
2

```

In [ ]:
import pandas as pd
import numpy as np

# Sample data
data = {
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'score': [12.5, 9.0, 16.5, np.nan, 9.0, 20.0, 14.5, np.nan, 8.0, 19.0]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Count NaN values in each column
nan_count=df.isna().sum().sum()

print("\nCount of NaN values in each column:")
print(nan_count)


Original DataFrame:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0

Count of NaN values in each column:
2


##22. Write a Pandas program to drop a list of rows from a specified DataFrame.
```
Sample data:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1


New DataFrame after removing 2nd & 4th rows:
   col1  col2  col3
0     1     4     7
1     4     5     8
3     4     7     0
```

In [ ]:
import pandas as pd

# Sample data
data = {
    'col1': [1, 4, 3, 4, 5],
    'col2': [4, 5, 6, 7, 8],
    'col3': [7, 8, 9, 0, 1]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("\nNew DataFrame after removing 2nd & 4th rows:")
print(df.drop([2,4]))

Original DataFrame:
   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1

New DataFrame after removing 2nd & 4th rows:
   col1  col2  col3
0     1     4     7
1     4     5     8
3     4     7     0


##23. . Write a Pandas program to convert DataFrame column type from string to datetime.

```

Sample data:
String Date:
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object


Original DataFrame (string to datetime):
           0
0 2000-03-11
1 2000-03-12
2 2000-03-13
```

In [ ]:
import pandas as pd

# Sample data
string_dates = pd.Series(['3/11/2000', '3/12/2000', '3/13/2000'])

print("String date:")
print(string_dates)

# Convert string dates to datetime
datetime_dates = pd.to_datetime(string_dates)

# Create DataFrame
df = pd.DataFrame(datetime_dates)

# Rename column if necessary
#df.columns = ['Date']

print("Original DataFrame (string to datetime):")
print(df)


String date:
0    3/11/2000
1    3/12/2000
2    3/13/2000
dtype: object
Original DataFrame (string to datetime):
           0
0 2000-03-11
1 2000-03-12
2 2000-03-13


##24. Write a Pandas program to find the row for where the value of a given column is maximum.

```
Sample Output:
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11
Row where col1 has maximum value:
4
Row where col2 has maximum value:
3
Row where col3 has maximum value:
2
```

In [ ]:
import pandas as pd

# Sample data
data = {
    'col1': [1, 2, 3, 4, 7],
    'col2': [4, 5, 6, 9, 5],
    'col3': [7, 8, 12, 1, 11]
}

# Create DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Find row index where col1 has maximum value
max_row_col1 = df['col1'].idxmax()
print("\nRow where col1 has maximum value:")
print(max_row_col1)

# Find row index where col2 has maximum value
max_row_col2 = df['col2'].idxmax()
print("\nRow where col2 has maximum value:")
print(max_row_col2)

# Find row index where col3 has maximum value
max_row_col3 = df['col3'].idxmax()
print("\nRow where col3 has maximum value:")
print(max_row_col3)


Original DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

Row where col1 has maximum value:
4

Row where col2 has maximum value:
3

Row where col3 has maximum value:
2


In [ ]:
# Find row index where each column has maximum value
max_row_index = df.idxmax()

print("\nRow where each column has maximum value:")
print(max_row_index)


Row where each column has maximum value:
col1    4
col2    3
col3    2
dtype: int64


##25. Write a Pandas program to get the datatypes of columns of a DataFrame.

```
Sample data:
Original DataFrame:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
.......
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
Data types of the columns of the said DataFrame:
attempts      int64
name         object
qualify      object
score       float64
dtype: object
```

In [ ]:
import pandas as pd
import numpy as np
# Sample data
data = {
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'score': [12.5, 9.0, 16.5, np.nan, 9.0, 20.0, 14.5, np.nan, 8.0, 19.0]
}

df=pd.DataFrame(data)
print("Original Data:")
print(df)
print("Data types of the columns of the said DataFrame:")
print(df.dtypes)

Original Data:
   attempts       name qualify  score
0         1  Anastasia     yes   12.5
1         3       Dima      no    9.0
2         2  Katherine     yes   16.5
3         3      James      no    NaN
4         2      Emily      no    9.0
5         3    Michael     yes   20.0
6         1    Matthew     yes   14.5
7         1      Laura      no    NaN
8         2      Kevin      no    8.0
9         1      Jonas     yes   19.0
Data types of the columns of the said DataFrame:
attempts      int64
name         object
qualify      object
score       float64
dtype: object


##26. Write a Pandas program to group by the first column and get second column as lists in rows.

```
Sample data:
Original DataFrame
col1 col2
0 C1 1
1 C1 2
2 C2 3
3 C2 3
4 C2 4
5 C3 6
6 C2 5


Group on the col1:
col1
C1 [1, 2]
C2 [3, 3, 4, 5]
C3 [6]
Name: col2, dtype: object
```

In [ ]:
data={
    'col1':['C1','C1','C2','C2','C2','C3','C2'],
    'col2':[1,2,3,3,4,6,5]
}
df=pd.DataFrame(data)
print("Original dataframe:")
print(df)

# Group by the first column and aggregate the second column into lists
grouped_df=df.groupby('col1')['col2'].apply(list)

print("Group in the col1:")
print(grouped_df)

Original dataframe:
  col1  col2
0   C1     1
1   C1     2
2   C2     3
3   C2     3
4   C2     4
5   C3     6
6   C2     5
Group in the col1:
col1
C1          [1, 2]
C2    [3, 3, 4, 5]
C3             [6]
Name: col2, dtype: object


##27  Write a Pandas program to count number of columns of a DataFrame.

```
Sample Output:
Original DataFrame
  col1 col2 col3
0  1    4   7
1  2    5   8
2  3    6   12
3  4    9   1
4  7    5   11

Number of columns:
3
```

In [ ]:
import pandas as pd

# Sample DataFrame
data = {'col1': [1, 2, 3, 4, 7],
        'col2': [4, 5, 6, 9, 5],
        'col3': [7, 8, 12, 1, 11]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("\nNumber of columns:")
print(df.shape[1])


Original DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6    12
3     4     9     1
4     7     5    11

Number of columns:
3


##28.  Write a Pandas program to get first n records of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

First 3 rows of the said DataFrame':
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
```


In [ ]:
import pandas as pd

# Sample DataFrame
data = {'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("\nFirst 3 rows of the said DataFrame:")
print(df.head(3))


Original DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

First 3 rows of the said DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8


##29. Write a Pandas program to get last n records of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

Last 3 rows of the said DataFrame':
col1 col2 col3
3 4 9 12
4 7 5 1
5 11 0 11
```

In [ ]:
import pandas as pd

# Sample DataFrame
data = {'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)
print("\nLast 3 rows of the said DataFrame:")
print(df.tail(3))


Original DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

Last 3 rows of the said DataFrame:
   col1  col2  col3
3     4     9    12
4     7     5     1
5    11     0    11


##30.  Write a Pandas program to get topmost n records within each group of a DataFrame.

```
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11

```
```
topmost n records within each group of a DataFrame:
col1 col2 col3
5 11 0 11
4 7 5 1
3 4 9 12
col1 col2 col3
3 4 9 12
2 3 6 8
1 2 5 5
4 7 5 1
col1 col2 col3
3 4 9 12
5 11 0 11
2 3 6 8
```

In [ ]:
import pandas as pd

# Sample DataFrame
data = {'col1': [1, 2, 3, 4, 7, 11],
        'col2': [4, 5, 6, 9, 5, 0],
        'col3': [7, 5, 8, 12, 1, 11]}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

print("topmost n records within each group of a DataFrame:")
# Get topmost n records within each group
for col in df:
  new_df=df.nlargest(3,col)
  print(new_df)

Original DataFrame:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
topmost n records within each group of a DataFrame:
   col1  col2  col3
5    11     0    11
4     7     5     1
3     4     9    12
   col1  col2  col3
3     4     9    12
2     3     6     8
1     2     5     5
   col1  col2  col3
3     4     9    12
5    11     0    11
2     3     6     8


##31. Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.

```
Sample Output:
Original DataFrame
W X Y Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

Add prefix:
A_W A_X A_Y A_Z
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

Add suffix:
W_1 X_1 Y_1 Z_1
0 68 78 84 86
1 75 85 94 97
2 86 96 89 96
3 80 80 83 72
4 66 86 86 83

```

In [ ]:
import pandas as pd
#sample Dataframe
data={'W':[68,75,86,80,66],
      'X':[78,85,96,80,86],
      'Y':[84,94,89,83,86],
      'Z':[86,97,96,72,83]
      }
df=pd.DataFrame(data)
#print dataframe
print("Original Dataframe:")
print(df)

#add a prefix '_A' to all columns of dataframe
add_prefix=df.add_prefix('A_')

#add a suffix '_1' to all columns of dataframe
add_suffix=df.add_suffix('_1')

print("\n\nAdd prefix")
print(add_prefix)
print("\n\nAdd suffix:")
print(add_suffix)

Original Dataframe:
    W   X   Y   Z
0  68  78  84  86
1  75  85  94  97
2  86  96  89  96
3  80  80  83  72
4  66  86  86  83


Add prefix
   A_W  A_X  A_Y  A_Z
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83


Add suffix:
   W_1  X_1  Y_1  Z_1
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83


##32. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.
```
Input:
{ 'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
'Age': [18, 22, 40, 50, 80, 5] }


Output:
Age group:
0 kids
1 adult
2 elderly
3 adult
4 elderly
5 kids
Name: age_groups, dtype: category
Categories (3, object): [kids < adult < elderly]
```

In [ ]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alberto Franco', 'Gino Mcneill', 'Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],
    'Age': [18, 22, 40, 50, 80]
}

df = pd.DataFrame(data)

print("Input:")
print(data)
# Define the bins and labels for age groups
bins = [0, 18, 65, df['Age'].max()]
labels = ['kids', 'adult', 'elderly']

# Convert continuous values of 'Age' column to categorical
df['age_groups'] = pd.cut(df['Age'], bins=bins, labels=labels)

print("Age group:")
print(df['age_groups'])


Input:
{'Name': ['Alberto Franco', 'Gino Mcneill', 'Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'], 'Age': [18, 22, 40, 50, 80]}
Age group:
0       kids
1      adult
2      adult
3      adult
4    elderly
Name: age_groups, dtype: category
Categories (3, object): ['kids' < 'adult' < 'elderly']


##33.Write a Pandas program to append rows to an existing DataFrame and display the combined data.

```** **
Test Data:
tudent_data1
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199


New Row(s)
student_id                  S6
name          Scarlette Fisher
marks                      205
dtype: object
```

In [ ]:
import pandas as pd

# Existing DataFrame
student_data1 = pd.DataFrame({
    'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
    'marks': [200, 210, 190, 222, 199]
})

# New row(s) to append
new_row = pd.DataFrame({
    'student_id': ['S6'],
    'name': ['Scarlette Fisher'],
    'marks': [205]
})

# Concatenate the existing DataFrame and the new row(s)
combined_data = pd.concat([student_data1, new_row], ignore_index=True)

#print original data frame
print("Test Data:\nStudent_data1")
print(student_data1)

#print New row i.e 'S6'
print("\nNew Row(s)")
print(combined_data.loc[5])

Test Data:
Student_data1
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199

New Row(s)
student_id                  S6
name          Scarlette Fisher
marks                      205
Name: 5, dtype: object


##34  Write a Pandas program to join the two given dataframes along rows and merge with another dataframe along the common column id.

```
Test Data:
student_data1:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
student_data2:
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201
```
```

exam_data:
   student_id  exam_id
0          S1       23
1          S2       45
2          S3       12
3          S4       67
4          S5       21
5          S7       55
6          S8       33
7          S9       14
8         S10       56
9         S11       83
10        S12       88
11        S13       12
```


In [ ]:
import pandas as pd

# Test Data
student_data1 = pd.DataFrame({
    'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
    'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
    'marks': [200, 210, 190, 222, 199]
})

student_data2 = pd.DataFrame({
    'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
    'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
    'marks': [201, 200, 198, 219, 201]
})

exam_data = pd.DataFrame({
    'student_id': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
    'exam_id': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]
})

# Concatenate student_data1 and student_data2 along rows
all_student_data = pd.concat([student_data1, student_data2], ignore_index=True)

# Merge all_student_data with exam_data along the common column 'student_id'
merged_data = pd.merge(all_student_data, exam_data, on='student_id')

print("Merged Data:")
print(merged_data)


Merged Data:
  student_id              name  marks  exam_id
0         S1  Danniella Fenton    200       23
1         S2      Ryder Storey    210       45
2         S3      Bryce Jensen    190       12
3         S4         Ed Bernal    222       67
4         S4  Scarlette Fisher    201       67
5         S5       Kwame Morin    199       21
6         S5  Carla Williamson    200       21
7         S7    Kaiser William    219       55
8         S8   Madeeha Preston    201       33
